config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "about", to: "home#about"
  resources "articles"
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_category
    has_many :categories, through: :article_category
    validates :title, presence: true
    validates :title, length: {minimum: 6, maximum: 100}
    validates :description, presence: true
    validates :description, length: {minimum: 10, maximum: 350}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/category.rb
class Category <ApplicationRecord
    has_many :article_category
    has_many :articles, through: :article_category
    validates :name, presence: true, 
                    uniqueness: true,
                    length: {minimum: 3, maximum: 25}
end

app/models/user.rb
class User < ApplicationRecord
    has_many :articles, dependent: :destroy
    before_save :downcaseEmail
    validates :username, presence: true, 
                    uniqueness: { case_sensitivity: false }, 
                    length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                    uniqueness: { case_sensitivity: false }, 
                    length: {maximum: 105},
                    format: { with: VALID_EMAIL_REGEX }
    has_secure_password

    private
    def downcaseEmail
        self.email = email.downcase
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:index, :show]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(page: params[:page],per_page: 5)
    end

    def show
    end

    def new
        @article = Article.new
    end

    def edit
    end

    def create
        @article = Article.new(article_params)
        @article.user = current_user
        if @article.save
            redirect_to article_path(@article), notice: "Article has been created successfully"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        @article.user = User.first
        if @article.update(article_params)
            redirect_to article_path(@article), notice: "Article has been updated successfully"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @article.delete
        redirect_to articles_path
    end

    private 
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.required(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
        if current_user != @article.user && !current_user.admin?
            flash[:alert] = "You can only edit or delete articles that you created"
            redirect_to @article
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update]
    before_action :require_admin, except: [:index, :show]

    def index
        @categories = Category.paginate(page: params[:page],per_page: 5)
    end
    
    def show
        @articles = @category.articles.paginate(page: params[:page],per_page:2)
    end

    def new
        @category = Category.new
    end

    def edit
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        if @category.update(category_params)
            flash[:notice] = "Category was successfully updated"
            redirect_to @category
        else
            render :new, status: :unprocessable_entity
        end
    end

    private
    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admin can perform this action"
            redirect_to categories_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        redirect_to articles_path if logged_in?
    end

    def about
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Logged in successfully"
            redirect_to user
        else
            flash.now[:alert] = "There was something wrong with your login detail"
            render 'new', status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update, :destroy]
    before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @users = User.paginate(page: params[:page],per_page: 5)

    end

    def show
        @articles = @user.articles.paginate(page: params[:page],per_page:2)
    end
    
    def new
        @user = User.new
    end

    def edit
    end

    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully sign up"
            session[:user_id] = @user.id
            redirect_to @user
        else
            render :new, status: :unprocessable_entity
        end
    end

    def update
        if @user.update(user_params)
            flash[:notice] = "Your account information has been successfully updated"
            redirect_to @user
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles successfully deleted"
        redirect_to articles_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end

    def require_user
        if !logged_in?
            flash[:alert] = "You must be logged in to perform that action"
            redirect_to login_path
        end
    end
    
    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or destroy your account"
            redirect_to @user
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def gravatar_for(user, options = { size: 80 })
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block shadow")
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_article.html.erb
<div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="font-italic card-header">
                        <% if article.user %>
                                by <%= link_to article.user.username, article.user %>
                        <% end %>
                        <% if article.categories.any? %>
                            <div class="mt=2"><%= render article.categories %></div>        
                        <% end %>    
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-decoration-none text-success" %></h5>
                        <p class="card-text"><%= truncate(article.description, length: 100) %></p>
                        <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                        <% if (logged_in? && (current_user == article.user || current_user.admin?)) %>
                            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-primary" %>
                            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                        <% end %>        
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words article.created_at %> time ago ,edited <%= time_ago_in_words article.updated_at %> time ago</small>
                    </div>
                </div>
            </div>
        </div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/error', obj: @article %>
            <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="form-group row mb-3">
                    <%= f.label :title, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article"%>
                    </div>
                </div>
                <div class="form-group row mb-3">
                    <%= f.label :description, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
                    </div>
                </div>
                <div class="form-group row mb-3">
                    <%= f.label :category, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.collection_select(:category_ids, Category.all, :id, :name, { prompt: "Make your selection from the list below (can be empty)" }, { multiple: true, size:3, class: "form-select rounded shadow" } ) %>
                    </div>
                </div>
                <div class="form-group d-flex justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
            <% end %>
        </div>
    </div>
</div>
<%= link_to "[ Cancel and return to article listing ]", articles_path, class: "d-flex justify-content-center text-info mb-3" %>

app/views/articles/edit.html.erb
<h1 class="mt-4 text-center">Edit a existing article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all article</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<div class="container">
    <% @articles.each do |article| %>
        <%= render "article", article: article %>
    <% end %>
</div>
<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title %></h1>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="font-italic card-header">
                    by <%= @article.user.username %>
                    <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
                    <% if @article.categories.any? %>
                        <div class="mt-2">
                            <%= render @article.categories %>
                        </div>
                    <% end %>
                </div>
                <div class="card-body">
                    <div class="card-text text-start"><%= simple_format @article.description %></div>
                    <% if logged_in? && current_user == @article.user || current_user.admin? %>
                        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-primary" %>
                        <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                    <% end %>        
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words @article.created_at %> time ago ,edited <%= time_ago_in_words @article.updated_at %> time ago</small>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category, class: "badge rounded-pill text-decoration-none bg-primary me-1" %>

app/views/categories/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/error', obj: @category %>
            <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="form-group row mb-3">
                    <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name"%>
                    </div>
                </div>
                <div class="form-group d-flex justify-content-center">
                    <%= f.submit class: "btn btn-outline-light btn-lg" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit category name</h1>

<%= render 'form' %>
<%= link_to "[ Cancel and return to category show page ]", @category, class: "d-flex justify-content-center text-info mb-3" %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>
<div class="container">
    <% @categories.each do |category| %>
        <div class="row justify-content-md-center">
            <div class="col-8 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to category.name, category, class: "text-decoration-none text-success" %></h5>        
                        <p class="card-text"><%= pluralize category.articles.count, "article" %></p>    
                    </div>
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words category.created_at %> time ago ,edited <%= time_ago_in_words category.updated_at %> time ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>
<div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create a new category</h1>

<%= render 'form' %>
<%= link_to "[ Cancel and return to category listing ]", categories_path, class: "d-flex justify-content-center text-info mb-3" %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin?  %>
    <div class="text-center mt-4">
        <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4"> Articles </h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<% @articles.each do |article| %>
    <%= render 'articles/article', article: article %>
<% end %>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/home/about.html.erb
<h1>This is about page</h1>
<%= link_to "Home", root_path %><br>
<%= link_to "Article listing", articles_path %>

app/views/home/index.html.erb
<div class="container" id="home-container">
    <div class="jumbotron container-fluid py-5 text-center text-white">
        <h1 class="display-5 fw-bold">Alpha blog</h1>
        <p class="fs-4">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content within the larger container</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg", role: "button" %>
    </div>
    <%= link_to "About", about_path %><br>
    <%= link_to "Article listing", articles_path %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Google", "https://www.google.com", class: "text-white"%></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% if flash.any? %>
    <div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-<%=name=="alert" ? "danger":"success"%> fade show alert-dismissible" role="alert">
            <%=msg%>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
    </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Blogger", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
              <li><%= link_to "Create new article", new_article_path, class: "dropdown-item" %></li>
            <% end %>  
            <li><%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "Create new category", new_category_path, class: "dropdown-item" %></li>
            <% end %>  
            <li><%= link_to "View categories", categories_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin) " if current_user.admin? %>Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile", current_user, class: "dropdown-item" %></li>
              <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><%= link_to "Delete profile", current_user, class: "dropdown-item text-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', logout_path, class: "nav-link", data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Log in", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Sign up", signup_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      </div>
      <form class="d-flex justify-content-end" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Code</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-100 d-flex flex-column">
    <%= render 'layouts/nav' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger fade show alert-dismissible" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
        <ul>
            <% obj.errors.full_messages.each do |message| %>
                <li><%=message%></li>
        <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/error', obj: @user %>
            <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
                <div class="form-group row mb-3">
                    <%= f.label :username, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username"%>
                    </div>
                </div>
                <div class="form-group row mb-3">
                    <%= f.label :email, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :email, rows: 10, class: "form-control shadow rounded", placeholder: "Enter a email" %>
                    </div>
                </div>
                <div class="form-group row mb-3">
                    <%= f.label :password, class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.password_field :password, rows: 10, class: "form-control shadow rounded", placeholder: "Choose a password" %>
                    </div>
                </div>
                <div class="form-group d-flex justify-content-center">
                    <%= f.submit (@user.new_record? ? "Sign up" : "Update account"), class: "btn btn-outline-light btn-lg" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4"> Edit your profile</h1>
<%= render 'form' %>

app/views/users/index.erb
<h1 class="text-center mt-4">Alpha Blogger</h1>

<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
<% @users.each do |user| %>
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
                <div class="font-italic card-header">
                    by <%= link_to user.username, user %>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to gravatar_for(user, size: 150), user %>
                    </h5>
                    <p class="card-text"><%= pluralize user.articles.count, "article" %></p>
                    <%= link_to "View profile", user, class: "btn btn-outline-success" %>
                    <% if logged_in? %>
                        <% if current_user == user %>
                            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-primary" %>
                        <% end %>
                        <% if current_user.admin? %>
                            <%= link_to "Delete profile", user,  class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                        <% end %>       
                    <% end %> 
                </div>
                <div class="card-footer text-muted">
                    <small>Joined <%= time_ago_in_words user.created_at %></small>
                </div>
            </div>
        </div>
    </div>
<% end %>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4"> Sign up for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"> <%=@user.username%> 's profile</h1>
<%= gravatar_for @user, size: 200 %>

<% if logged_in? && current_user == @user %>
    <div class="text-center mt-4">
        <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
    </div>
<% end %>

<h3 class="text-center mt-4"> Articles </h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<% @articles.each do |article| %>
    <%= render 'articles/article', article: article %>
<% end %>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>